# Kubernetes code snippets
[[snippets]]
  description = "Quickly retrieve imperative commands to create k8s resources."
  command = "kubectl run -h | grep '# ' -A2"
  tag = ["kubernetes", "kubectl"]
  output = "List of different ways to create k8s resources imperatively using kubectl."

[[snippets]]
  description = "Quickly retrieve imperative commands to create k8s resources."
  command = "kubectl describe pod <pod-name=nginx> | grep -i events -A 10"
  tag = ["kubernetes", "kubectl"]
  output = "Last 10 events on a selected pod."

[[snippets]]
  description = "Quickly find kube api server settings."
  command = "ps -ef --forest | grep kube-apiserver | grep <setting=admission-plugins>"
  tag = ["kubernetes", "kubectl"]
  output = ""

[[snippets]]
  description = "Display all k8s resources."
  command = "kubectl api-resources -owide"
  tag = ["kubernetes", "kubectl"]
  output = ""

[[snippets]]
  description = "Get encoded csr in a proper format"
  command = "cat <csr=myuser.csr> | base64 | tr -d \"\\n\""
  tag = ["kubernetes", "kubectl"]
  output = "Token ready to be pasted in the token field of Kubernetes dashboard for example."





















