# Commands
[[snippets]]
  description = "Quickly retrieve imperative commands to create k8s resources."
  command = "kubectl run -h | grep '# ' -A2"
  tag = ["kubernetes", "kubectl"]
  output = "list of different ways to create k8s resources imperatively using kubectl"

[[snippets]]
  description = "Quickly retrieve imperative commands to create k8s resources."
  command = "kubectl describe pod <pod-name> | grep -i events -A 10"
  tag = ["kubernetes", "kubectl"]
  output = "Check last 10 events on pod"

  # Bookmarks
[[snippets]]
    description = "START: cheatsheet and useful commands"
    command = "open https://kubernetes.io/docs/reference/kubectl/cheatsheet/"
    tag = ["kubernetes", "bookmark"]
    output = ""
[[snippets]]
    description = "SPEC: audit policy YAML spec"
    command = "open https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/audit/audit-policy.yaml"
    tag = ["kubernetes", "bookmark"]
    output = ""
[[snippets]]
    description = "SPEC: cronjob YAML spec"
    command = "open https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/storage/pv-claim.yaml"
    tag = ["kubernetes", "bookmark"]
    output = ""
[[snippets]]
    description = "SPEC: sample nginx YAML deployment spec"
    command = "open https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/simple_deployment.yaml"
    tag = ["kubernetes", "bookmark"]
    output = ""
[[snippets]]
    description = "SPEC: minimalistic ingress YAML spec"
    command = "open https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/minimal-ingress.yaml"
    tag = ["kubernetes", "bookmark"]
    output = ""
